export const NCERT_CHAPTERS: Record<string, Record<string, string[]>> = {
  "12": {
    "Physics": [
      "Electric Charges and Fields",
      "Electrostatic Potential and Capacitance",
      "Current Electricity",
      "Moving Charges and Magnetism",
      "Magnetism and Matter",
      "Electromagnetic Induction",
      "Alternating Current",
      "Electromagnetic Waves",
      "Ray Optics and Optical Instruments",
      "Wave Optics",
      "Dual Nature of Radiation and Matter",
      "Atoms",
      "Nuclei",
      "Semiconductor Electronics"
    ],
    "Chemistry": [
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "The d-and f-Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols and Ethers",
      "Aldehydes, Ketones and Carboxylic Acids",
      "Amines",
      "Biomolecules"
    ],
    "Biology": [
      "Sexual Reproduction in Flowering Plants",
      "Human Reproduction",
      "Reproductive Health",
      "Principles of Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Evolution",
      "Human Health and Disease",
      "Microbes in Human Welfare",
      "Biotechnology: Principles and Processes",
      "Biotechnology and its Applications",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and Conservation"
    ],
    "Maths": [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Application of Derivatives",
      "Integrals",
      "Application of Integrals",
      "Differential Equations",
      "Vector Algebra",
      "Three Dimensional Geometry",
      "Linear Programming",
      "Probability"
    ],
    "English": [
      "The Last Lesson",
      "Lost Spring",
      "Deep Water",
      "The Rattrap",
      "Indigo",
      "Poets and Pancakes",
      "The Interview",
      "Going Places",
      "My Mother at Sixty-six (Poem)",
      "Keeping Quiet (Poem)",
      "A Thing of Beauty (Poem)",
      "A Roadside Stand (Poem)",
      "Aunt Jennifer's Tigers (Poem)"
    ]
  },
  "11": {
    "Physics": [
      "Units and Measurements",
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Laws of Motion",
      "Work, Energy and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory",
      "Oscillations",
      "Waves"
    ],
    "Chemistry": [
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "Organic Chemistry – Some Basic Principles and Techniques",
      "Hydrocarbons"
    ],
    "Biology": [
      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Structural Organisation in Animals",
      "Cell: The Unit of Life",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration"
    ],
    "Maths": [
      "Sets",
      "Relations and Functions",
      "Trigonometric Functions",
      "Complex Numbers and Quadratic Equations",
      "Linear Inequalities",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequences and Series",
      "Straight Lines",
      "Conic Sections",
      "Introduction to Three Dimensional Geometry",
      "Limits and Derivatives",
      "Statistics",
      "Probability"
    ],
    "English": [
      "The Portrait of a Lady",
      "A Photograph (Poem)",
      "“We’re Not Afraid to Die... if We Can All Be Together”",
      "Discovering Tut: the Saga Continues",
      "The Laburnum Top (Poem)",
      "The Voice of the Rain (Poem)",
      "Childhood (Poem)",
      "The Adventure",
      "Silk Road",
      "Father to Son (Poem)"
    ]
  },
  "10_TN_EN": {
    "Science": [
      "Laws of Motion",
      "Optics",
      "Thermal Physics",
      "Electricity",
      "Acoustics",
      "Nuclear Physics",
      "Atoms and Molecules",
      "Periodic Classification of Elements",
      "Solutions",
      "Types of Chemical Reactions",
      "Carbon and its Compounds",
      "Plant Anatomy and Plant Physiology",
      "Structural Organisation of Animals",
      "Transportation in Plants and Circulation in Animals",
      "Nervous System",
      "Plant and Animal Hormones",
      "Reproduction in Plants and Animals",
      "Genetics",
      "Origin and Evolution of Life",
      "Breeding and Biotechnology",
      "Health and Diseases",
      "Environmental Management",
      "Visual Communication"
    ],
    "Maths": [
      "Relations and Functions",
      "Numbers and Sequences",
      "Algebra",
      "Geometry",
      "Coordinate Geometry",
      "Trigonometry",
      "Mensuration",
      "Statistics and Probability"
    ]
  },
  "10_TN_TM": {
    "Science": [
      "இயக்க விதிகள்",
      "ஒளியியல்",
      "வெப்ப இயற்பியல்",
      "மின்னோட்டவியல்",
      "ஒலியியல்",
      "அணுக்கரு இயற்பியல்",
      "அணுக்களும் மூலக்கூறுகளும்",
      "தனிமங்களின் ஆவர்த்தன வகைப்பாடு",
      "கரைசல்கள்",
      "வேதிவினைகளின் வகைகள்",
      "கார்பனும் அதன் சேர்மங்களும்",
      "தாவர அமைப்பியல் மற்றும் தாவர செயலியல்",
      "விலங்கினங்களின் அமைப்பு நிலைகள்",
      "தாவரங்களின் கடத்துதல் மற்றும் விலங்குகளின் சுற்றோட்டம்",
      "நரம்பு மண்டலம்",
      "தாவர மற்றும் விலங்கு ஹார்மோன்கள்",
      "தாவரங்கள் மற்றும் விலங்குகளில் இனப்பெருக்கம்",
      "மரபியல்",
      "உயிரின் தோற்றமும் பரிணாமமும்",
      "இனக்கலப்பு மற்றும் உயிரித்தொழில்நுட்பவியல்",
      "உடல் நலம் மற்றும் நோய்கள்",
      "சுற்றுச்சூழல் மேலாண்மை",
      "காட்சித் தொடர்பு"
    ],
    "Maths": [
      "உறவுகளும் சார்புகளும்",
      "எண்களும் தொடர்வரிசைகளும்",
      "இயற்கணிதம்",
      "வடிவியல்",
      "ஆயத்தொலை வடிவியல்",
      "முக்கோணவியல்",
      "அளவியல்",
      "புள்ளியியலும் நிகழ்தகவும்"
    ]
  },
  "8_TN_EN": {
    "Science": [
      "Measurement",
      "Force and Pressure",
      "Light",
      "Heat",
      "Electricity",
      "Sound",
      "Magnetism",
      "Universe and Space Science",
      "Matter around us",
      "Changes around us",
      "Air",
      "Atomic Structure",
      "Water",
      "Acids and Bases",
      "Chemistry in Everyday Life",
      "Microorganisms",
      "Plant Kingdom",
      "Organisation of Life",
      "Movements in Animals",
      "Reaching the Age of Adolescence",
      "Crop Production and Management",
      "Conservation of Plants and Animals",
      "Libre Office Calc"
    ],
    "Maths": [
      "Numbers",
      "Measurements",
      "Algebra",
      "Life Mathematics",
      "Geometry",
      "Statistics",
      "Information Processing"
    ]
  },
  "8_TN_TM": {
    "Science": [
      "அளவீட்டியல்",
      "விசையும் அழுத்தமும்",
      "ஒளியியல்",
      "வெப்பம்",
      "மின்னியல்",
      "ஒலியியல்",
      "காந்தவியல்",
      "அண்டம் மற்றும் விண்வெளி அறிவியல்",
      "நம்மைச் சுற்றியுள்ள பருப்பொருள்கள்",
      "நம்மைச்சுற்றி நிகழும் மாற்றங்கள்",
      "காற்று",
      "அணு அமைப்பு",
      "நீர்",
      "அமிலங்கள் மற்றும் காரங்கள்",
      "அன்றாட வாழ்வில் வேதியியல்",
      "நுண்ணுயிரிகள்",
      "தாவர உலகம்",
      "உயிரினங்களின் ஒருங்கமைவு",
      "விலங்குகளின் இயக்கம்",
      "வளரிளம் பருவமடைதல்",
      "பயிர்ப் பெருக்கம் மற்றும் மேலாண்மை",
      "தாவரங்கள் மற்றும் விலங்குகளைப் பாதுகாத்தல்",
      "லிப்ரே ஆபீஸ் கால்க்"
    ],
    "Maths": [
      "எண்கள்",
      "அளவைகள்",
      "இயற்கணிதம்",
      "வாழ்வியல் கணிதம்",
      "வடிவியல்",
      "புள்ளியியல்",
      "தகவல் செயலாக்கம்"
    ]
  },
  "9_TN_EN": {
    "Science": [
      "Measurement",
      "Motion",
      "Fluids",
      "Electric charge and Electric current",
      "Magnetism and Electromagnetism",
      "Light",
      "Heat",
      "Sound",
      "Universe",
      "Matter Around Us",
      "Atomic Structure",
      "Periodic Classification of Elements",
      "Chemical Bonding",
      "Acids, Bases and Salts",
      "Carbon and its Compounds",
      "Applied Chemistry",
      "Animal Kingdom",
      "Organisation of Tissues",
      "Plant Physiology",
      "Organ Systems in Animals",
      "Nutrition and Health",
      "World of Microbes",
      "Economic Biology",
      "Environmental Science",
      "LibreOffice Impress"
    ],
    "Maths": [
      "Set Language",
      "Real Numbers",
      "Algebra",
      "Geometry",
      "Coordinate Geometry",
      "Trigonometry",
      "Mensuration",
      "Statistics",
      "Probability"
    ]
  },
  "9_TN_TM": {
    "Science": [
      "அளவீடு",
      "இயக்கம்",
      "பாய்மங்கள்",
      "மின்னூட்டமும் மின்னோட்டமும்",
      "காந்தவியல் மற்றும் மின்காந்தவியல்",
      "ஒளி",
      "வெப்பம்",
      "ஒலி",
      "அண்டம்",
      "நம்மைச் சுற்றியுள்ள பருப்பொருள்கள்",
      "அணு அமைப்பு",
      "தனிமங்களின் வகைப்பாட்டு அட்டவணை",
      "வேதிப்பிணைப்பு",
      "அமிலங்கள், காரங்கள் மற்றும் உப்புகள்",
      "கார்பனும் அவற்றின் சேர்மங்களும்",
      "பயன்பாட்டு வேதியியல்",
      "விலங்குலகம்",
      "திசுக்களின் அமைப்பு",
      "தாவர உலகம் (தாவர செயலியல்)",
      "விலங்குகளின் உறுப்பு மண்டலங்கள்",
      "ஊட்டச்சத்து மற்றும் ஆரோக்கியம்",
      "நுண்ணுயிரிகளின் உலகம்",
      "பொருளாதார உயிரியல்",
      "சூழ்நிலை அறிவியல்",
      "லிப்ரே ஆபீஸ் இம்ப்ரஸ்"
    ],
    "Maths": [
      "கண மொழி",
      "மெய்யெண்கள்",
      "இயற்கணிதம்",
      "வடிவியல்",
      "ஆயத்தொலை வடிவியல்",
      "முக்கோணவியல்",
      "அளவியல்",
      "புள்ளியியல்",
      "நிகழ்தகவு"
    ]
  },
  "11_TN_EN": {
    "Physics": [
      "Nature of Physical World and Measurement",
      "Kinematics",
      "Laws of Motion",
      "Work, Energy and Power",
      "Motion of System of Particles and Rigid Bodies",
      "Gravitation",
      "Properties of Matter",
      "Heat and Thermodynamics",
      "Kinetic Theory of Gases",
      "Oscillations",
      "Waves"
    ],
    "Chemistry": [
      "Basic Concepts of Chemistry and Chemical Calculations",
      "Quantum Mechanical Model of Atom",
      "Periodic Classification of Elements",
      "Hydrogen",
      "Alkali and Alkaline Earth Metals",
      "Gaseous State",
      "Thermodynamics",
      "Physical and Chemical Equilibrium",
      "Solutions",
      "Chemical Bonding",
      "Fundamentals of Organic Chemistry",
      "Basic Rules of Organic Reactions",
      "Hydrocarbons",
      "Environmental Chemistry"
    ],
    "Biology": [
      "The Living World",
      "Kingdom Animalia",
      "Biomolecules",
      "Tissue Level of Organisation",
      "Organ and Organ System in Animals",
      "Digestion and Absorption",
      "Breathing and Respiration",
      "Body Fluids and Circulation",
      "Excretory Products and their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration",
      "Cell: The Unit of Life",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis",
      "Respiration",
      "Plant Growth and Development"
    ],
    "Maths": [
      "Sets, Relations and Functions",
      "Basic Algebra",
      "Trigonometry",
      "Combinatorics and Mathematical Induction",
      "Two Dimensional Analytical Geometry",
      "Sequences and Series",
      "Matrices and Determinants",
      "Vector Algebra",
      "Differential Calculus - Limits and Continuity",
      "Differential Calculus - Differentiability and Methods of Differentiation",
      "Integral Calculus",
      "Introduction to Probability Theory"
    ]
  },
  "11_TN_TM": {
    "Physics": [
      "இயற்பியல் உலகத்தின் தன்மையும் அளவீட்டியலும்",
      "இயக்கவியல்",
      "இயக்க விதிகள்",
      "வேலை, ஆற்றல் மற்றும் திறன்",
      "துகள்களின் அமைப்பு மற்றும் திண்மப்பொருள்களின் இயக்கம்",
      "ஈர்ப்பியல்",
      "பருப்பொருளின் பண்புகள்",
      "வெப்பமும் வெப்ப இயக்கவியலும்",
      "வாயுக்களின் இயக்கவியற் கொள்கை",
      "அலைவுகள்",
      "அலைகள்"
    ],
    "Chemistry": [
      "வேதியியலின் அடிப்படைக் கருத்துக்கள் மற்றும் வேதிமுறைக் கணக்கீடுகள்",
      "அணுவின் குவாண்டம் இயக்கவியல் மாதிரி",
      "தனிமங்களின் வகைப்பாட்டு அட்டவணை",
      "ஹைட்ரஜன்",
      "கார மற்றும் காரமண் உலோகங்கள்",
      "வாயு நிலை",
      "வெப்ப இயக்கவியல்",
      "இயற்பியல் மற்றும் வேதிச்சமநிலை",
      "கரைசல்கள்",
      "வேதிப்பிணைப்பு",
      "கரிம வேதியியலின் அடிப்படைகள்",
      "கரிம வினைகளின் அடிப்படைக் கருத்துக்கள்",
      "ஹைட்ரோகார்பன்கள்",
      "சுற்றுச்சூழல் வேதியியல்"
    ],
    "Biology": [
      "உயிருலகம்",
      "விலங்குலகம்",
      "உயிரி மூலக்கூறுகள்",
      "திசு அளவிலான கட்டமைப்பு",
      "விலங்குகளின் உறுப்பு மற்றும் உறுப்பு மண்டலங்கள்",
      "செரிமானம் மற்றும் உட்கிரகித்தல்",
      "சுவாசம்",
      "உடல் திரவங்கள் மற்றும் சுற்றோட்டம்",
      "கழிவுநீக்கப் பொருட்கள் மற்றும் அவற்றின் நீக்கம்",
      "இடப்பெயர்ச்சி மற்றும் இயக்கம்",
      "நரம்புக்கட்டுப்பாடு மற்றும் ஒருங்கிணைப்பு",
      "வேதி ஒருங்கிணைப்பு",
      "செல்: வாழ்வின் அலகு",
      "செல் சுழற்சி மற்றும் செல் பகுப்பு",
      "தாவரங்களில் கடத்துதல்",
      "கனிம ஊட்டம்",
      "ஒளிச்சேர்க்கை",
      "சுவாசித்தல்",
      "தாவர வளர்ச்சி மற்றும் வளர்ச்சி ஒழுங்குபடுத்திகள்"
    ],
    "Maths": [
      "கணங்கள், தொடர்புகள் மற்றும் சார்புகள்",
      "அடிப்படை இயற்கணிதம்",
      "முக்கோணவியல்",
      "சேர்ப்பியல் மற்றும் கணிதத் தொகுத்தறிதல்",
      "இருபரிமாண பகுமுறை வடிவியல்",
      "தொடர்முறைகளும் தொடர்களும்",
      "அணிகளும் அணிக்கோவைகளும்",
      "வெக்டர் இயற்கணிதம்",
      "வகை நுண்கணிதம் - எல்லைகள் மற்றும் தொடர்ச்சித்தன்மை",
      "வகை நுண்கணிதம் - வகைமை மற்றும் வகையிடல் முறைகள்",
      "தொகை நுண்கணிதம்",
      "நிகழ்தகவு கோட்பாட்டின் அறிமுகம்"
    ]
  },
  "12_TN_EN": {
    "Physics": [
      "Electrostatics",
      "Current Electricity",
      "Magnetism and Magnetic Effects of Electric Current",
      "Electromagnetic Induction and Alternating Current",
      "Electromagnetic Waves",
      "Ray Optics",
      "Wave Optics",
      "Dual Nature of Radiation and Matter",
      "Atomic and Nuclear Physics",
      "Electronics and Communication Systems",
      "Recent Developments in Physics"
    ],
    "Chemistry": [
      "Metallurgy",
      "p-Block Elements - I",
      "p-Block Elements - II",
      "Transition and Inner Transition Elements",
      "Coordination Chemistry",
      "Solid State",
      "Chemical Kinetics",
      "Ionic Equilibrium",
      "Electrochemistry",
      "Surface Chemistry",
      "Hydroxy Compounds and Ethers",
      "Carbonyl Compounds and Carboxylic Acids",
      "Organic Nitrogen Compounds",
      "Biomolecules",
      "Chemistry in Everyday Life"
    ],
    "Biology": [
      "Reproduction in Organisms",
      "Sexual Reproduction in Flowering Plants",
      "Principles of Inheritance and Variation",
      "Molecular Genetics",
      "Evolution",
      "Human Health and Diseases",
      "Microbes in Human Welfare",
      "Biotechnology: Principles and Processes",
      "Applications of Biotechnology",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and Conservation",
      "Environmental Issues"
    ],
    "Maths": [
      "Applications of Matrices and Determinants",
      "Complex Numbers",
      "Theory of Equations",
      "Inverse Trigonometric Functions",
      "Two Dimensional Analytical Geometry-II",
      "Applications of Vector Algebra",
      "Applications of Differential Calculus",
      "Differentials and Partial Derivatives",
      "Applications of Integral Calculus",
      "Ordinary Differential Equations",
      "Probability Distributions",
      "Discrete Mathematics"
    ]
  },
  "12_TN_TM": {
    "Physics": [
      "நிலைமின்னியல்",
      "மின்னோட்டவியல்",
      "காந்தவியல் மற்றும் மின்னோட்டத்தின் காந்த விளைவுகள்",
      "மின்காந்த தூண்டலும் மாற்று மின்னோட்டமும்",
      "மின்காந்த அலைகள்",
      "கதிர் ஒளியியல்",
      "அலை ஒளியியல்",
      "கதிர்வீச்சு மற்றும் பருப்பொருளின் இருமைத்தன்மை",
      "அணு மற்றும் அணுக்கரு இயற்பியல்",
      "குறை கடத்தி எலக்ட்ரானிக்ஸ்",
      "இயற்பியலின் அண்மைக்கால வளர்ச்சிகள்"
    ],
    "Chemistry": [
      "உலோகவியல்",
      "ப-தொகுதி தனிமங்கள் - I",
      "ப-தொகுதி தனிமங்கள் - II",
      "இடைநிலை மற்றும் உள் இடைநிலைத் தனிமங்கள்",
      "அணைவு வேதியியல்",
      "திண்ம நிலை",
      "வேதி வினை வேகவியல்",
      "அயனிச் சமநிலை",
      "மின் வேதியியல்",
      "பரப்பு வேதியியல்",
      "ஹைட்ராக்ஸி சேர்மங்கள் மற்றும் ஈதர்கள்",
      "கார்பனைல் சேர்மங்கள் மற்றும் கார்பாக்சிலிக் அமிலங்கள்",
      "நைட்ரஜன் கரிமச் சேர்மங்கள்",
      "உயிரி மூலக்கூறுகள்",
      "அன்றாட வாழ்வில் வேதியியல்"
    ],
    "Biology": [
      "உயிரிகளின் இனப்பெருக்கம்",
      "பூக்கும் தாவரங்களில் பாலின இனப்பெருக்கம்",
      "பாரம்பரியக் கடத்தல் கொள்கைகள் மற்றும் மாறுபாடுகள்",
      "மூலக்கூறு மரபியல்",
      "பரிணாமம்",
      "மனித நலன் மற்றும் நோய்கள்",
      "மனித நலனில் நுண்ணுயிரிகள்",
      "உயிரி தொழில்நுட்பவியல்: கொள்கைகளும் செயல்முறைகளும்",
      "உயிரி தொழில்நுட்பவியலின் பயன்பாடுகள்",
      "உயிரினங்களும் இனக்கூட்டமும்",
      "சூழ்நிலை மண்டலம்",
      "பல்லுயிர் தன்மை மற்றும் பாதுகாப்பு",
      "சுற்றுச்சூழல் பிரச்சினைகள்"
    ],
    "Maths": [
      "அணிகள் மற்றும் அணிக்கோவைகளின் பயன்பாடுகள்",
      "கலப்பு எண்கள்",
      "சமன்பாட்டியல்",
      "நேர்மாறு முக்கோணவியல் சார்புகள்",
      "இருபரிமாண பகுமுறை வடிவியல்-II",
      "வெக்டர் இயற்கணிதத்தின் பயன்பாடுகள்",
      "வகை நுண்கணிதத்தின் பயன்பாடுகள்",
      "வகையீடுகள் மற்றும் பகுதி வகைக்கெழுக்கள்",
      "தொகை நுண்கணிதத்தின் பயன்பாடுகள்",
      "சாதாரண வகைக்கெழுச் சமன்பாடுகள்",
      "நிகழ்தகவு பரவல்கள்",
      "தனிநிலை கணிதம்"
    ]
  },
  "10": {
    "Science": [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-metals",
      "Carbon and its Compounds",
      "Life Processes",
      "Control and Coordination",
      "How do Organisms Reproduce?",
      "Heredity",
      "Light – Reflection and Refraction",
      "The Human Eye and the Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Our Environment"
    ],
    "Maths": [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability"
    ],
    "Social Science": [
      "The Rise of Nationalism in Europe",
      "Nationalism in India",
      "The Making of a Global World",
      "The Age of Industrialisation",
      "Print Culture and the Modern World",
      "Resources and Development",
      "Forest and Wildlife Resources",
      "Water Resources",
      "Agriculture",
      "Minerals and Energy Resources",
      "Manufacturing Industries",
      "Lifelines of National Economy",
      "Power Sharing",
      "Federalism",
      "Gender, Religion and Caste",
      "Political Parties",
      "Outcomes of Democracy",
      "Development",
      "Sectors of the Indian Economy",
      "Money and Credit",
      "Globalisation and the Indian Economy",
      "Consumer Rights"
    ],
    "English": [
      "A Letter to God",
      "Nelson Mandela: Long Walk to Freedom",
      "Two Stories about Flying",
      "From the Diary of Anne Frank",
      "Glimpses of India",
      "Madam Rides the Bus",
      "The Sermon at Benares",
      "The Proposal",
      "Dust of Snow (Poem)",
      "Fire and Ice (Poem)",
      "A Tiger in the Zoo (Poem)",
      "How to Tell Wild Animals (Poem)",
      "The Ball Poem (Poem)",
      "Amanda! (Poem)",
      "The Trees (Poem)",
      "Fog (Poem)",
      "The Tale of Custard the Dragon (Poem)",
      "For Anne Gregory (Poem)"
    ]
  },
  "9": {
    "Science": [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure",
      "Atoms and Molecules",
      "Structure of the Atom",
      "The Fundamental Unit of Life",
      "Tissues",
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound",
      "Improvement in Food Resources"
    ],
    "Maths": [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
      "Linear Equations in Two Variables",
      "Introduction to Euclid’s Geometry",
      "Lines and Angles",
      "Triangles",
      "Quadrilaterals",
      "Circles",
      "Heron’s Formula",
      "Surface Areas and Volumes",
      "Statistics"
    ],
    "Social Science": [
      "The French Revolution",
      "Socialism in Europe and the Russian Revolution",
      "Nazism and the Rise of Hitler",
      "Forest Society and Colonialism",
      "Pastoralists in the Modern World",
      "India – Size and Location",
      "Physical Features of India",
      "Drainage",
      "Climate",
      "Natural Vegetation and Wildlife",
      "Population",
      "What is Democracy? Why Democracy?",
      "Constitutional Design",
      "Electoral Politics",
      "Working of Institutions",
      "Democratic Rights",
      "The Story of Village Palampur",
      "People as Resource",
      "Poverty as a Challenge",
      "Food Security in India"
    ],
    "English": [
      "The Fun They Had",
      "The Sound of Music",
      "The Little Girl",
      "A Truly Beautiful Mind",
      "The Snake and the Mirror",
      "My Childhood",
      "Reach for the Top",
      "Kathmandu",
      "If I Were You",
      "The Road Not Taken (Poem)",
      "Wind (Poem)",
      "Rain on the Roof (Poem)",
      "The Lake Isle of Innisfree (Poem)",
      "A Legend of the Northland (Poem)",
      "No Men Are Foreign (Poem)",
      "On Killing a Tree (Poem)",
      "A Slumber Did My Spirit Seal (Poem)"
    ]
  },
  "8": {
    "Science": [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Force and Pressure",
      "Friction",
      "Sound",
      "Chemical Effects of Electric Current",
      "Some Natural Phenomena",
      "Light"
    ],
    "Maths": [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Understanding Quadrilaterals",
      "Data Handling",
      "Squares and Square Roots",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorisation",
      "Introduction to Graphs"
    ],
    "Social Science": [
      "How, When and Where",
      "From Trade to Territory",
      "Ruling the Countryside",
      "Tribals, Dikus and the Vision of a Golden Age",
      "When People Rebel",
      "Civilising the \"Native\", Educating the Nation",
      "Women, Caste and Reform",
      "The Making of the National Movement: 1870s-1947",
      "Resources",
      "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
      "Agriculture",
      "Industries",
      "Human Resources",
      "The Indian Constitution",
      "Understanding Secularism",
      "Parliament and the Making of Laws",
      "Judiciary",
      "Understanding Our Criminal Justice System",
      "Marginalisation Confronted",
      "Public Facilities",
      "Law and Social Justice"
    ],
    "English": [
      "The Best Christmas Present in the World",
      "The Tsunami",
      "Glimpses of the Past",
      "Bepin Choudhury's Lapse of Memory",
      "The Summit Within",
      "This is Jody's Fawn",
      "A Short Monsoon Diary",
      "The Great Stone Face",
      "The Ant and the Cricket (Poem)",
      "Geography Lesson (Poem)",
      "Macavity: The Mystery Cat (Poem)",
      "The Last Bargain (Poem)",
      "The School Boy (Poem)",
      "On the Grasshopper and Cricket (Poem)"
    ]
  }
};
